### PR TITLE
added the possibility of using annotations for icinga2 chart and icingaweb2 chart services

### PR DESCRIPTION
**Pull request by Ramshield**
I personally use annotations in Services, but noticed this wasn't possible in the icinga2 and icingaweb2 chart. So I added the possibility.

### CODE REVIEW

**Comment by Ramshield** [comment]
I have  signed.

**Comment by lippserd** [comment]
@cla-bot check

**Comment by Ramshield** [comment]
@cla-bot check

**Comment by Ramshield** [comment]
Not sure what is going wrong, but I have signed the agreement, and got the signed document in my e-mail as I write this.

**Comment by lippserd** [comment]
> Not sure what is going wrong, but I have signed the agreement, and got the signed document in my e-mail as I write this.

Unfortunately, the document is worth nothing if it does not contain valid data. However, I can understand if you do not want to provide the information. You are then welcome to close the PR.

**Comment by lippserd** [comment]
Many thanks for your contribution anyway!

**Pull request closed without merging**
