### PR TITLE
Icinga2 set ICINGA_DISABLE_CONFD env variable

### LINKED ISSUE #5: [Bug]: Icinga2 needs cleaning up of local config upon (re-)start
### Affected Chart

icinga-stack

### Which version of the app contains the bug?

0.1.0

### Please describe your problem

If config is deployed to Icinga via director/api, it might clash with local config being present upon restart of the container.

Example:

Create a host template `generic-host` via Director, kill the pod.

### PR DESCRIPTION
**Pull request by CanisLupusLupus**
This PR resolves #5.

It adds new configuration parameter to Icinga 2 chart  which sets ICINGA_DISABLE_CONFD environment variable of Icinga2 docker to enable or disable `include_recursive "conf.d"` directive in icinga2.conf.

### CODE REVIEW

**Comment by CanisLupusLupus** [comment]
CLA signed

**Comment by martialblog** [comment]
Hi, thanks for the PR. We will have a look at it.

**Comment by bobapple** [comment]
@cla-bot check

**Comment by mocdaniel** [comment]
Thank you very much for your contribution!

**Review by mocdaniel — APPROVED** [review]

**Pull request merged**
