### PR TITLE
icinga-stack: extraEnvVars value for icinga2/icingadb

### PR DESCRIPTION
**Pull request by loicwinkopp**
Value to add extra environment variables in icinga2 container, useful to fill variables like PGHOST, PGPORT, PGDATABASE, PGUSER, PGPASSWORD, etc.

### CODE REVIEW

**Comment by loicwinkopp** [comment]
Done!

**Comment by lippserd** [comment]
@cla-bot check

**Comment by martialblog** [comment]
@mocdaniel looks alright to me. In fact, might be good to add this to other charts as well?

**Comment by loicwinkopp** [comment]
@martialblog @mocdaniel I added it for icingadb (seemed more relevant to me than for icinga web) and added tests

**Review by mocdaniel — APPROVED** [review]
LGTM, thanks for your contribution @loicwinkopp

**Pull request merged**
