### PR TITLE
[Docs] Repo name and value missing for helm installation

### PR DESCRIPTION
**Pull request by mainstreamtt**
I just discovered that the Helm repo name and a value is missing for the helm installation command. :smiley:

### CODE REVIEW

**Comment by mainstreamtt** [comment]
> Thank you for your pull request. Before we can look at it, you'll need to sign a Contributor License Agreement (CLA).
> 
> **Please follow instructions at https://icinga.com/company/contributor-agreement to sign the CLA.**
> 
> After that, please reply here with a comment and we'll verify.
> 
> Contributors that have not signed yet: @mainstreamtt

CLA signed

**Comment by martialblog** [comment]
@mainstreamtt Hey, thanks for the PR! We will have a look at it.

**Review by mocdaniel — APPROVED** [review]

**Comment by mocdaniel** [comment]
@bobapple can you trigger the CLA bot to check again?

**Comment by bobapple** [comment]
CLA has not been signed

**Comment by mainstreamtt** [comment]
> CLA has not been signed

Hey
I got a mail that it is signed.
Document ID: bc34ccf2693cff1468dc729c73eb9cc2b9fffd28

**Comment by bobapple** [comment]
@cla-bot check

**Comment by mocdaniel** [comment]
Thanks again for the fix @mainstreamtt I will go ahead and merge the changes.

**Pull request merged**
